import React, { FC, useMemo } from "react"

interface SvgMessageProps {
  /**
   * The raw SVG string content to be rendered.
   */
  svgContent: string
  /**
   * Optional metadata that might contain information about the SVG,
   * like its source or description. Not directly used for rendering
   * but could be useful for tooltips or accessibility in the future.
   */
  meta?: Record<string, any>
}

/**
 * A React component designed to render SVG content within a chat message.
 * It uses `dangerouslySetInnerHTML` to inject the SVG string into the DOM.
 *
 * Security Note: This component should only be used with SVG content
 * generated by trusted tool sources, as `dangerouslySetInnerHTML` can
 * expose the application to XSS vulnerabilities if used with untrusted input.
 * The SVG content from tools like Mermaid (via mermaid.ink) is generally
 * considered safe as it's structured XML for rendering, not executable script.
 * However, always validate or sanitize if the source is questionable.
 *
 * @component
 * @param {SvgMessageProps} props - The props for the component.
 * @returns {React.ReactElement | null} The React element representing the rendered SVG,
 * or null if svgContent is not provided.
 *
 * @example
 * const svgString = "<svg width='100' height='100'><circle cx='50' cy='50' r='40' stroke='green' stroke-width='4' fill='yellow' /></svg>";
 * <SvgMessage svgContent={svgString} />
 */
export const SvgMessage: FC<SvgMessageProps> = ({ svgContent, meta }) => {
  // Moved useMemo to the top level before any conditional returns.
  const isPotentiallySvg = useMemo(() => {
    if (!svgContent || typeof svgContent !== "string") {
      return false // Not a string, so not SVG for our purposes here.
    }
    const trimmedContent = svgContent.trim().toLowerCase()
    return (
      trimmedContent.startsWith("<svg") && trimmedContent.endsWith("</svg>")
    )
  }, [svgContent])

  if (!svgContent || typeof svgContent !== "string") {
    console.warn("SvgMessage: svgContent is missing or not a string.", {
      svgContent,
      meta
    })
    return (
      <div className="p-2 text-sm text-red-500 dark:text-red-400">
        Error: Invalid SVG content provided.
      </div>
    )
  }

  if (!isPotentiallySvg) {
    console.warn("SvgMessage: Content does not appear to be valid SVG.", {
      meta
    })
    return (
      <div className="p-2 text-sm text-orange-500 dark:text-orange-400">
        Warning: The provided content might not be a valid SVG diagram.
        Displaying as raw text.
        <pre className="mt-2 whitespace-pre-wrap break-all rounded bg-gray-100 p-2 text-xs dark:bg-gray-800">
          {svgContent}
        </pre>
      </div>
    )
  }

  return (
    <div
      className="mermaid-svg-container max-w-full overflow-auto rounded bg-white p-2 shadow dark:bg-gray-800"
      // Using dangerouslySetInnerHTML to render the SVG string.
      // Ensure that svgContent comes from a trusted source.
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svgContent }}
      role="img"
      aria-label={meta?.description || meta?.toolName || "SVG Diagram"}
    />
  )
}

SvgMessage.displayName = "SvgMessage"
